# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Nexys4DDR_Master.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_bin2bcd_0_0_0/design_2_bin2bcd_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_bin2bcd_0_0_0 || ORIG_REF_NAME==design_2_bin2bcd_0_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_bin2bcd_0_1_0/design_2_bin2bcd_0_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_bin2bcd_0_1_0 || ORIG_REF_NAME==design_2_bin2bcd_0_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_divizor_ceas_0_0/design_2_divizor_ceas_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_divizor_ceas_0_0 || ORIG_REF_NAME==design_2_divizor_ceas_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_numarator_59_0_0_0/design_2_numarator_59_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_numarator_59_0_0_0 || ORIG_REF_NAME==design_2_numarator_59_0_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_numarator_59_0_1_0/design_2_numarator_59_0_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_numarator_59_0_1_0 || ORIG_REF_NAME==design_2_numarator_59_0_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_afisare_7seg_0_0_0/design_2_afisare_7seg_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_afisare_7seg_0_0_0 || ORIG_REF_NAME==design_2_afisare_7seg_0_0_0} -quiet] -quiet

# XDC: c:/Users/student/Downloads/laboratoaresoc/lab_2/lab3_324CB/lab3_324CB.gen/sources_1/bd/design_2/design_2_ooc.xdc
