version: '3'
services:
  lab4-db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=books
    volumes:
      - lab4-db-volume:/var/lib/postgresql/data
    networks:
      - lab4-db-network
      - lab4-adminer-network
    deploy:
      restart_policy:
        condition: on-failure
  lab4-adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - lab4-adminer-network
    deploy:
      restart_policy:
        condition: on-failure
  lab4-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PGUSER=admin
      - PGPASSWORD=admin
      - PGDATABASE=books
      - PGHOST=lab4-db
      - PGPORT=5432
    ports:
      - '5555:80'
    networks:
      - lab4-db-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  lab4-db-network:
  lab4-adminer-network:

volumes:
  lab4-db-volume:
