build:
		touch tema2.in
		gcc -g -o tema2 main.c functions.c task1.c task2.c task3.c
run:
		./tema2
clean:
		rm tema2
		rm *.out *.in
valgrind:
		valgrind --leak-check=yes --track-origins=yes ./tema2