# This is an auxiliary method used to generate our strings by length and alphabetically
# E.g: (b | aa)* = [b, aa, bb, aab, bbb, aaaa, ...]
def convert_to_sorted_set(lst: [str]) -> [str]:
    """Converts a list to a sorted set"""
    crt_lst = list(set(lst))
    return sorted(crt_lst, key=lambda x: (len(x), x))


# Global variable used to threshold the number of Star items
INNER_STAR_NO_ITEMS = 3


class Regex:
    """Base class for Regex ADT"""

    def __str__(self) -> str:
        """Returns the string representation of the regular expression"""
        pass

    def gen(self) -> [str]:
        """Return a representative set of strings that the regular expression can generate"""
        pass

    def __len__(self) -> str:
        """Returns the length of the regular expression"""
        pass

    def eval_gen(self):
        """Prints the set of strings that the regular expression can generate"""
        pass


# Implementati Clasa Void dupa blueprint-ul de mai sus
class Void(Regex):
    """Represents the empty regular expression"""

    # Va returna Void ca string
    def __str__(self) -> str:
        return "Void"

    # Va genera un obiect din Python corespunzatoar clasei void
    def gen(self) -> [str]:
        return []

    def __len__(self):
        return 0

    def eval_gen(self):
        print("Void generates nothing")


# Implementati Clasa Epsilon-String (Empty) dupa blueprint-ul de mai sus
class Empty(Regex):
    """Represents the empty string regular expression"""

    # Va returna Empty ca string
    def __str__(self) -> str:
        return "Empty"

    # Va returna o lista corespunzatoare a ce stringuri produce sirul vid
    def gen(self) -> [str]:
        return [""]

    # Va returna lungimea corespunzatoare sirului vid
    def __len__(self) -> int:
        return 0

    def eval_gen(self):
        print(f"Empty string has length {len(self)} generates ''.")


# Implementati functionalitatile necesare pentru Clasa Symbol dupa blueprint-ul de mai sus
class Symbol(Regex):
    """Represents a symbol in the regular expression"""

    def __init__(self, char: str):
        self.char = char

    # Completati metodele __str__ si gen pentru clasa Symbol
    def __str__(self) -> str:
        self.words = [self.char]
        return self.char

    def gen(self) -> [str]:
        return [self.char]

    def __len__(self) -> int:
        return 1

    def eval_gen(self):
        self.gen()

        # Dorim sa pastram in atributul words al clasei curente stringurile generate cu gen(self)
        return f"Symbol {self.char} has length {len(self)} generates {self.words}"


# Implementati functionalitatile necesare pentru Clasa Union dupa blueprint-ul de mai sus
class Union(Regex):
    """Represents the union of two regular expressions"""

    def __init__(self, *arg: [Regex]):
        self.components = arg

    # Completati metodele __str__, gen, __len__ si eval_gen pentru clasa Union

    # Hint: Look at the str.join method to create (expr1|expr2|...)
    def __str__(self) -> str:
        return " | ".join([str(comp) for comp in self.components])

    def gen(self) -> [str]:
        return [word for comp in self.components for word in comp.gen()]

    # We will consider the len of a Union as the max length of its components
    def __len__(self) -> int:
        return max(len(comp) for comp in self.components)

    # Dupa modelul de la Symbol, vom dori ca urmatoarele eval sa implementeze
    # return "Class {varianta toString() a clasei) has length {len(self)} and generates {self.words}"
    def eval_gen(self) -> str:
        print(f"Union {str(self)} has length {len(self)} and generates {self.gen()}")
        return self.gen()


# Implementati functionalitatile necesare pentru Clasa Concat dupa blueprint-ul de mai sus
class Concat(Regex):
    """Represents the concatenation of two regular expressions"""

    def __init__(self, *arg: [Regex]):
        self.components = arg

    # Completati metodele __str__, gen, __len__ si eval_gen pentru clasa Concat
    def __str__(self) -> str:
        return "".join([f"({str(comp)})" for comp in self.components])

    def gen(self) -> [str]:
        words = [""]
        for comp in self.components:
            words = [word + new_word for word in words for new_word in comp.gen()]
        return words

    def __len__(self) -> int:
        return sum(len(comp) for comp in self.components)

    def eval_gen(self) -> str:
        print(f"Concat {str(self)} has length {len(self)} and generates {self.gen()}")
        return self.gen()


# Implementati functionalitatile necesare pentru Clasa Star dupa blueprint-ul de mai sus
class Star(Regex):
    """Represents the Kleene star (zero or more repetitions) of a regular expression"""

    def __init__(self, regex: Regex):
        self.regex = regex

        # To memorize the base words generated by the regex inside the star, we store them in a list
        self.base_words = [""]
        self.words = []

    # Completati metodele __str__, gen, __len__, eval_gen pentru clasa Star
    def __str__(self) -> str:
        return f"({str(self.regex)})*"

    def gen(self, no_items=10) -> [str]:
        self.words = self.base_words[:]
        current_words = self.base_words[:]
        for _ in range(no_items):
            new_words = []
            for word in current_words:
                for new_word in self.regex.gen():
                    combined = word + new_word
                    new_words.append(combined)
            self.words.extend(new_words)
            current_words = new_words
        return self.words[:no_items]

    # To ease your implementation we will consider a big number e.g. 1000000 as Infinity
    def __len__(self) -> int:
        return 1000000

    def eval_gen(self, no_items=10):
        print(f"Star {str(self)} has length {len(self)} and generates {self.gen(no_items)}")
        return self.gen(no_items)


if __name__ == "__main__":
    r1 = Symbol('a')
    r2 = Symbol('b')
    regex_union = Union(r1, r2)
    regex_union.eval_gen()

    e2 = Union(Symbol('a'), Symbol('b'), Symbol('c'))
    e4 = Concat(r1, e2)
    e4.eval_gen()

    e5 = Concat(e2, e2, r2)
    e5.eval_gen()

    star_ex = Star(r1)
    star_ex.eval_gen()

    regex_concat = Concat(regex_union, star_ex)
    regex_concat.eval_gen()

    last_expr = Concat(Star(Union(Symbol('a'), Symbol('b'))), Symbol('b'), Star(Symbol('c')))
    last_expr.eval_gen()
